### ISSUE TITLE
 [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS]

### ISSUE THREAD

**Issue by xp44mm** [jayphelps/webpack-rxjs-externals#19]
Although the software is working properly, the webpack interface has changed and is recommended to update this package.

(node:1956) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like `({context, request}, cb) => { ... }`
(Use \`node --trace-deprecation ...\` to show where the warning was created)

```
$ node -v
v14.16.0
```

```json
"webpack": "5.33.2",
```

see also : https://webpack.js.org/configuration/externals/#function

**Comment by Den-dp** [comment]
Added PR #23 to fix this
